;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Skill.ActiveE",DevComment="")
+GameplayTagList=(Tag="Character.Skill.ActiveQ",DevComment="")
+GameplayTagList=(Tag="Character.Skill.DefaultA",DevComment="")
+GameplayTagList=(Tag="Character.Skill.DefaultB",DevComment="")
+GameplayTagList=(Tag="Character.Skill.DefaultC",DevComment="")
+GameplayTagList=(Tag="Character.Skill.DefaultD",DevComment="")
+GameplayTagList=(Tag="Character.Skill.Heavy",DevComment="")
+GameplayTagList=(Tag="Character.State.Climbing",DevComment="")
+GameplayTagList=(Tag="Character.State.DefaultAttack",DevComment="")
+GameplayTagList=(Tag="Character.State.Gliding",DevComment="")
+GameplayTagList=(Tag="Character.State.Idle",DevComment="")
+GameplayTagList=(Tag="Character.State.Interaction",DevComment="")
+GameplayTagList=(Tag="Character.State.Jump",DevComment="")
+GameplayTagList=(Tag="Character.State.Run",DevComment="")
+GameplayTagList=(Tag="Character.State.Walk",DevComment="")
+GameplayTagList=(Tag="Player.Input.E",DevComment="")
+GameplayTagList=(Tag="Player.Input.Interaction",DevComment="")
+GameplayTagList=(Tag="Player.Input.MouseLeft",DevComment="")
+GameplayTagList=(Tag="Player.Input.MouseLeft.Hold",DevComment="")
+GameplayTagList=(Tag="Player.Input.Q",DevComment="")

